# Generated by Django 3.2.19 on 2023-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
