# Generated by Django 3.2.19 on 2023-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='recipe_images/default_recipe.jpg', null=True, upload_to='recipe_images'),
        ),
    ]
