# Generated by Django 3.2.19 on 2023-07-11 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.URLField(default='https://source.unsplash.com/8l8Yl2ruUsg', max_length=1000, validators=[django.core.validators.URLValidator()]),
        ),
    ]
